openapi: 3.0.2
info:
  title: Generic blockchain node REST API
  version: 0.0.1
paths:
  '/api/v0/account/{account_id}':
    get:
      descriptions: Gets account state
      parameters:
        - name: account_id
          in: path
          required: true
          schema:
            description: Hex-encoded account ID
            type: string
            pattern: '[0-9a-fA-F]+'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                required:
                  - value
                  - counter
                properties:
                  delegation:
                    description: Hex-encoded stake pool ID this account is delegating to
                    type: string
                    pattern: '[0-9a-fA-F]+'
                  value:
                    description: Current balance of this account
                    type: integer
                    minimum: 0
                  counter:
                    description: Number of transactions performed with this account
                    type: integer
                    minimum: 0
                  last_rewards:
                    description: the last rewards
                    type: object
                    properties:
                      epoch:
                        description: the last epoch that distributed rewards to this account
                        type: integer
                        minimum: 0
                      reward:
                        description: the total amount of rewards received for the associated epoch
                        type: integer
                        minimum: 0
              examples:
                application/json:
                  value: |
                    {
                      "counter": 1,
                      "delegation": "c780f14f9782770014d8bcd514b1bc664653d15f73a7158254730c6e1aa9f356",
                      "value": 990,
                      "last_rewards":
                        {
                          "epoch": 42,
                          "reward": 2028
                        }
                    }
        '404':
          description: Account with given ID was not found

