
name: Api GH Deploy

# Run on each push to master
on:
  push:
    branches: [ master ]
    paths:
      - 'doc/api/*.yaml'

jobs:
  api_gh:
    runs-on: ubuntu-latest
    name: Testing public name
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # use the public name of the action
      - name: redoc-cli test
        uses: seeebiii/redoc-cli-github-action@v9
        with:
          args: 'bundle doc/api/v0.yaml -o v0.html'

      - name: check result
        run: |
          ls -al
          test -f v0.html || (echo "Missing v0.html from previous step." && exit 1)

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
