name: Spectral Lint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  spectralChecks:
    name: Spectral checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Spectral checks
        uses: stoplightio/spectral-action@v0.5.5
        with:
          file_glob: ./*.yaml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          spectral_ruleset: 'spectral:oas'
  test:
    name: Lint OpenAPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: l-lin/spectral-comment-action@0.1.0
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file-glob: ./*.yaml
