name: Spectral Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  spectralChecks:
    name: Spectral checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Spectral checks
        uses: ./
        with:
          file_glob: ./**/*.yml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          spectral_ruleset: 'spectral:oas'
