name: API Check
on:
  push:
    paths:
      - 'doc/api/*.yaml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: stoplightio/spectral-action@v0.6.0
        with:
          file_glob: doc/api/*.yaml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          spectral_ruleset: ''
