name: API Lint
on:
  push:
    branches: [ master ]
    paths:
      - 'api/*.yaml'
  pull_request:
    branches: [ master ]
    paths:
      - 'api/*.yaml'
jobs:
  spectralChecks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: stoplightio/spectral-action@v0.5.5
        with:
          file_glob: api/*.yaml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          spectral_ruleset: 'spectral:oas'
