name: Spectral Lint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  spectralChecks:
    name: Spectral checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: stoplightio/spectral-action@v0.5.5
      - name: Spectral checks
        uses: ./
        with:
          file_glob: ./**/*.yaml
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          spectral_ruleset: 'spectral:oas'
